# Generated by Django 5.1.7 on 2025-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
