# Generated by Django 4.2.17 on 2025-02-19 21:51

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('yoga', 'Yoga'), ('mental_health', 'Mental Health'), ('recipes', 'Recipes'), ('motivation', 'Motivation'), ('qna', 'QnA'), ('challenges', 'Challenges')], default='fitness', max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_images/', validators=[community.models.validate_image_size])),
                ('video', models.FileField(blank=True, null=True, upload_to='community_videos/', validators=[community.models.validate_video_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
