# Generated by Django 5.1.7 on 2025-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
