# Generated by Django 5.1.7 on 2025-03-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_profile_name_alter_profile_age_alter_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
    ]
